# Generated by Django 4.2.7 on 2023-12-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_school',
            fields=[
                ('sname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slocation', models.CharField(max_length=100)),
                ('sprinciple', models.CharField(max_length=100)),
            ],
        ),
    ]
